# Generated by Django 3.2.2 on 2021-05-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ong', '0002_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
    ]
